name: chronos
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies: 
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  flutter_bloc:
  intl:
  qr_flutter:
  google_maps_flutter:
  geocoding:
  geolocator:
  google_mlkit_face_detection:
  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  camera: ^0.11.2
  permission_handler: ^11.1.0
  google_fonts: ^6.1.0
  web: any
  shared_preferences:
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
